spring:
  datasource:
    password: 1234
    username: book
    url: jdbc:postgresql://localhost:5439/
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

